#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D
export _JAVA_AWT_WM_NONREPARTENTING=1

xsetroot -cursor_name Qogir-dark



# Polybar
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
xfce4-power-manager &
sh ~/bat_notify.sh
